image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

Build:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG || echo Could not fetch $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG from registry.
    - >
      docker build \
        --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG \
        --pull \
        -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG \
        .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

e2e:
  stage: test
  allow_failure: true
  when: manual
  script:
    - source scripts/test.sh

Demo1:
  stage: deploy
  services:
    - docker:dind
  environment:
    name: demo1
    url: https://demo4591891495012598120529813.webcaptioner.com
  script:
    - source scripts/deploy.sh
  when: manual

Staging:
  stage: deploy
  services:
    - docker:dind
  environment:
    name: staging
    url: https://staging.webcaptioner.com
  script:
    - source scripts/deploy.sh

Production:
  stage: deploy
  services:
    - docker:dind
  environment:
    name: production
    url: https://webcaptioner.com
  script:
    - source scripts/deploy.sh
  when: manual
