version: '3'

tasks:

  install:
    desc: "install npm dependencies"
    dir: '{{.USER_WORKING_DIR}}/app'
    cmds:
    - npm i

  serve:
    desc: "run webcaptioner locally"
    dir: '{{.USER_WORKING_DIR}}/app'
    cmds:
    - npm run dev
  
  start:
    desc: "start prod build"
    dir: '{{.USER_WORKING_DIR}}/app'
    cmds:
    - npm i
    - npm run build
    - npm run start

  build:
    desc: "build container image"
    cmds:
    - docker build -t webcaptioner .

  run:
    desc: "run latest container image"
    cmds:
    - docker stop demo
    - docker rm demo
    - docker run -p 8080:8080 --name demo webcaptioner:latest

  deploy:
    desc: "deploy to remote server"
    cmds:
    - fly deploy --ha=false
