version: '3'

tasks:

  serve:
    desc: "run webcaptioner locally"
    dir: '{{.USER_WORKING_DIR}}/app'
    cmds:
    - npm run dev
  
  deploy:
    dir: '{{.USER_WORKING_DIR}}/app'
    cmds:
    - npm i
    - npm run build
    - npm run start

  build:
    cmds:
    - docker build -t webcaptioner .

  run:
    cmds:
    - docker stop demo
    - docker rm demo
    - docker run -p 3000:3000 --name demo webcaptioner:latest

